version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/**/*"
      - "/libs/**/*"
      - "/packages/**/*"
      - "/tools/**/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "nx"
        versions: ["*"]
      - dependency-name: "@nx/*"
        versions: ["*"]
