name: '🐞 Bug Report'
description: Report a bug to help me improve _Famiglio_
title: '[BUG] <short description>'
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide a clear and concise description of the problem.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: What went wrong?
      placeholder: 'A clear and concise description of the bug.'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps needed to reproduce the issue.
      placeholder: |
        1. Run '...'
        2. Call endpoint '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: 'I expected the app to ...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or Logs
      description: Attach screenshots or logs if applicable.
      placeholder: 'Paste logs or drag-and-drop screenshots here.'

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Describe your setup (OS, Node.js, etc.)
      placeholder: 'Alma Linux 9, Ubuntu 22.04, Node.js 22.x, etc'
